apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw-api
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz/ready"
    service.beta.kubernetes.io/port_80_health-probe_protocol: http
    service.beta.kubernetes.io/port_80_health-probe_port: "15021"
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: "demo.gloo.love"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - group: gateway.networking.k8s.io
            kind: HTTPRoute